Report failed builds

diff --git a/aws/sqs/process b/aws/sqs/process
--- a/aws/sqs/process
+++ b/aws/sqs/process
@@ -3,6 +3,14 @@
 
 # Builds a PR based on a message received from SQS
 
+function reportFailure {
+  if [[ $? != 0 ]]; then
+    echo "Build Failure"
+    URL=$URL BRANCH=$HEAD HEAD=$HEAD_SHA ./github/checks/fail
+    exit
+  fi
+}
+
 JSON_RESPONSE=$(aws sqs receive-message --queue-url "$QUEUE_URL" --message-attribute-names All)
 
 if [[ -z $JSON_RESPONSE ]]; then
@@ -31,9 +39,9 @@ fi
 # Before each build, we lock the message for 20 minutes + 10 seconds
 #   (our maximum allowed build time + a grace period)
 aws sqs change-message-visibility --receipt-handle "$RECEIPT_HANDLE" --queue-url "$QUEUE_URL" --visibility-timeout 1210
-REF="$BASE" ./bench
+REF="$BASE" ./bench || reportFailure
 aws sqs change-message-visibility --receipt-handle "$RECEIPT_HANDLE" --queue-url "$QUEUE_URL" --visibility-timeout 1210
- PR="$PR"   ./bench
+ PR="$PR"   ./bench || reportFailure
 
 # Now that we are done building, we only need to lock the message for long
 # enough to generate our report. If something fails, we want the message to
